dist: trusty
sudo: false
language: java
jdk: oraclejdk8
branches:
  except:
   - /^backup/.*$/
   - /^unfinished/.*$/
after_success:
- ./upload.sh
before_install:
- '[ "$TRAVIS_PULL_REQUEST" == "false" ] && openssl aes-256-cbc -K $encrypted_1bdf8aa8fca7_key -iv $encrypted_1bdf8aa8fca7_iv -in secring.gpg.enc -out secring.gpg -d || echo "no decryption for pull requests"'
